FROM nvcr.io/nvidia/tritonserver:24.12-py3

RUN python3 -m pip install --no-cache-dir --index-url https://download.pytorch.org/whl/cu126 torch torchvision && \
    python3 -m pip install --no-cache-dir transformers pillow safetensors huggingface_hub einops kornia timm

COPY model_repository /models
